# org: kevinnk
# app: bookflight
# service: bookflight
# frameworkVersion: "3"

# provider:
#   name: aws
#   runtime: nodejs18.x
#   region: us-east-1

# functions:

# custom:
#   scriptable:
#     hooks:
#       before:package:createDeploymentArtifacts: make build
#   appSync:
#     name: ${self:service}-api
#     authentication:
#       type: AMAZON_COGNITO_USER_POOLS
#       config:
#         userPoolId: !ImportValue ${opt:stage, self:provider.stage, 'dev'}-UserPoolID
#     schema:
#       - "shared/graphql/*.graphql"
#       - "services/flights/api_public/schema/*.graphql"
#       - "services/flights/api_admin/schema/*.graphql"

# package:
#   individually: true

# plugins:
#   - serverless-scriptable-plugin
#   - serverless-import-plugin
#   - serverless-appsync-plugin
#   - serverless-prune-plugin

service: bookflight
frameworkVersion: "3"
plugins:
  - serverless-import-plugin
  - serverless-scriptable-plugin
  - serverless-appsync-plugin
  - serverless-prune-plugin
provider:
  name: aws
  region: "eu-central-1"
  stage: ${opt:stage, 'dev'}

custom:
  import:
    - shared/serverless/provider.yml
    - services/flight/serverless/resolvers/resolver.yml

appSync:
  name: ${self:service}-api
  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: !ImportValue ${opt:stage, self:provider.stage, 'dev'}-UserPoolID
  schema:
    - "services/flight/serverless/schema/*.graphql"
