org: kevinnk
app: bookflight
service: bookflight
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  addFlight:
    package:
      artifact: ./bin/addFlight.zip
    handler: bootstrap
    runtime: provided.al2
    events:
      - http:
          path: addFlight
          method: post
  getFlights:
    package:
      artifact: ./bin/getFlights.zip
    handler: bootstrap
    runtime: provided.al2
    events:
      - http:
          path: getFlights
          method: get

custom:
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: make build
  appSync:
    name: ${self:service}-api
    authentication:
      type: AMAZON_COGNITO_USER_POOLS
      config:
        userPoolId: !ImportValue ${opt:stage, self:provider.stage, 'dev'}-UserPoolID
    schema:
      - "shared/graphql/*.graphql"
      - "services/flights/api_public/schema/*.graphql"
      - "services/flights/api_admin/schema/*.graphql"

package:
  individually: true

plugins:
  - serverless-scriptable-plugin
  - serverless-import-plugin
  - serverless-appsync-plugin
  - serverless-prune-plugin
